/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package make.friend;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import make.friend.components.Lobby;
import make.friend.components.Settings;

public class App{
    public static void main(String[] args) {
        new Settings();
        new Lobby();

        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306",
                    "root",
                    "1234"
            );

            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(
                    "show databases"
            );

            while (rs.next()) {
                System.out.println(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}
